//===----------------------------------------------------------------------===//
// Ported from Go's standard library @ go1.26.5 — `sort.Sort`'s pdqsort, which is
// `src/sort/zsortinterface.go` plus the entry point and helpers in `src/sort/sort.go`.
//
// ## Why the sorting algorithm itself has to be ported
//
// Go's `sort.Sort` and `slices.SortFunc` are **not stable**, so the order of elements
// their comparator calls equal is whatever the algorithm leaves behind. Normally that
// does not matter. It matters here because two of PromQL's comparators are not valid
// strict weak orderings at all:
//
//   * `vectorByValueHeap.Less` is `if IsNaN(vi) { return true }; return vi < vj`, so
//     `Less(i, j)` and `Less(j, i)` are BOTH true when both are NaN — and a NaN sorts
//     before everything including itself.
//   * `natsort.Compare("a1", "a01")` and `Compare("a01", "a1")` are both true, so
//     `sort_by_label`'s comparator returns -1 in both directions.
//
// With an inconsistent comparator the output is not "some permutation of the sorted
// order" — it is *this* algorithm's permutation. Swift's `sort(by:)` has undefined
// behaviour on such a predicate and would be free to trap. So the algorithm is the
// contract, and it is ported here rather than approximated.
//
// ## One implementation covers both of Go's
//
// `src/sort/zsortinterface.go` and `src/slices/zsortanyfunc.go` are both generated from
// the same template by `gen_sort_variants.go`, and they are identical apart from how the
// comparison is spelled — `data.Less(i, j)` versus `cmp(data[i], data[j]) < 0`. So one
// index-based routine taking `less` and `swap` closures reproduces both exactly:
//
//     sort.Sort(data)            -> GoSort.sort(count:less:swap:) with data's Less
//     sort.Sort(sort.Reverse(d)) -> the same, with the arguments to Less flipped
//     slices.SortFunc(x, cmp)    -> the same, with less = { cmp(x[$0], x[$1]) < 0 }
//
// Verified by normalising the two generated files against each other; they differ only
// in signatures. If a future Go release diverges them, this file has to split.
//
// ## The fixtures pin a Go TOOLCHAIN, not just Prometheus
//
// Every other corpus in this repo is pinned to prometheus v3.13.2. This one is pinned to
// the Go release the oracle is built with, because the tie-break order is the standard
// library's. `Fixtures/gocompat/sort.jsonl` is regenerated by CI with whatever Go it has,
// so a toolchain whose pdqsort changed would fail there rather than silently drift. Go
// has kept this algorithm since 1.19; `sort.Stable`'s `symMerge`/`rotate` are NOT ported
// because nothing in the ported surface calls them.
//
// ## 36 negative controls, 34 of which break — including two that break by CRASHING
//
// Sampling `choosePivot` at `a + l - 1` instead of `a + l/4*3`, and recursing on the
// larger side instead of the smaller, both trap on an index. Worth noting because a
// "crash" from a control is a pass, and the sweep's first classifier called them
// inconclusive: the crash kills the run before the summary line it was grepping for.
//
// The one perturbation whose survival was NOT a corpus gap:
// `breakPatterns`' `length >= 8` guard. `breakPatterns` is only ever called from the top
// of pdqsort's loop, *after* the `length <= 12` insertion-sort return — so its argument is
// always at least 13 and the floor can be anything up to that. Dead by construction.
//
// And one that looked like a gap and was not:
// `partialInsertionSort`'s left shift is `for j := i - 1; j >= 1; j--` — bounded by **1**,
// not by `a`, so on a sub-range it can compare and swap `data[a-1]`, outside the range it
// was given. For a consistent comparator that is harmless and unobservable: when
// `partialInsertionSort` runs with `a > 0`, `data[a-1]` is a pivot that partitioning has
// already placed at or below everything in `[a, b)`, so `less(a, a-1)` is false and the
// loop stops where the tidier spelling would never have started. It takes an
// INCONSISTENT comparator to tell them apart — a NaN inside a sub-range that starts above
// zero. The corpus grew `nanTail`, `nanHead` and `nearlySortedNaN` for exactly that, and
// the control now breaks. So the bound is upstream's and is load-bearing; do not tidy it.
//===----------------------------------------------------------------------===//

/// Go: `sort`'s pdqsort, exposed the way Swift can use it.
///
/// Every entry point takes an element count plus `less`/`swap` closures over indices, so
/// the caller keeps ownership of the storage — which is also what lets one routine stand
/// in for both of Go's generated variants.
public enum GoSort {

    /// Go: `sortedHint` — what `choosePivot` learned about the run it sampled.
    private enum SortedHint {
        case unknown
        case increasing
        case decreasing
    }

    /// Go: `xorshift`, seeded from a length rather than from a clock — which is why
    /// `breakPatterns` is deterministic and can be pinned at all.
    private struct Xorshift {
        var state: UInt64

        init(_ seed: Int) { state = UInt64(bitPattern: Int64(seed)) }

        mutating func next() -> UInt64 {
            state ^= state << 13
            state ^= state >> 7
            state ^= state << 17
            return state
        }
    }

    /// Go: `math/bits.Len` — the minimum bits needed to represent `v`, 0 for 0.
    @inlinable
    public static func bitsLen(_ v: UInt) -> Int {
        v == 0 ? 0 : UInt.bitWidth - v.leadingZeroBitCount
    }

    /// Go: `nextPowerOfTwo` — `1 << bits.Len(length)`, so it is strictly greater than
    /// `length` when `length` is already a power of two.
    private static func nextPowerOfTwo(_ length: Int) -> UInt {
        UInt(1) << UInt(bitsLen(UInt(length)))
    }

    /// Go: `sort.Sort` — pdqsort over `0..<count`.
    ///
    /// `limit` starts at `bits.Len(uint(n))`, the number of bad pivots tolerated before
    /// the fallback to heapsort.
    public static func sort(
        count n: Int,
        less: (Int, Int) -> Bool,
        swap: (Int, Int) -> Void
    ) {
        if n <= 1 {
            return
        }
        pdqsort(0, n, bitsLen(UInt(n)), less, swap)
    }

    /// `sort.Sort(sort.Reverse(data))` — Go's `reverse` wrapper is one method that
    /// swaps the arguments, so this is the whole of it.
    public static func sortReverse(
        count n: Int,
        less: @escaping (Int, Int) -> Bool,
        swap: (Int, Int) -> Void
    ) {
        sort(count: n, less: { less($1, $0) }, swap: swap)
    }

    /// Go: `slices.SortFunc` — the same algorithm with `cmp(a, b) < 0` for `Less`.
    ///
    /// `cmp` returning 0 for distinct elements is exactly the case whose outcome the
    /// algorithm decides, so this must not be replaced with `Array.sort(by:)`.
    public static func sortFunc<E>(_ x: inout [E], _ cmp: (E, E) -> Int) {
        let n = x.count
        if n <= 1 {
            return
        }
        // The closures capture `x` by way of `withUnsafeMutableBufferPointer` so that
        // `less` and `swap` see each other's writes, which the algorithm requires.
        x.withUnsafeMutableBufferPointer { buf in
            pdqsort(
                0, n, bitsLen(UInt(n)),
                { cmp(buf[$0], buf[$1]) < 0 },
                { buf.swapAt($0, $1) })
        }
    }

    // MARK: - The algorithm

    /// Go: `insertionSort` — `data[a..<b]`.
    private static func insertionSort(
        _ a: Int, _ b: Int, _ less: (Int, Int) -> Bool, _ swap: (Int, Int) -> Void
    ) {
        var i = a + 1
        while i < b {
            var j = i
            while j > a && less(j, j - 1) {
                swap(j, j - 1)
                j -= 1
            }
            i += 1
        }
    }

    /// Go: `siftDown` — the heap property on `data[lo..<hi]`, rooted at `first`.
    private static func siftDown(
        _ lo: Int, _ hi: Int, _ first: Int, _ less: (Int, Int) -> Bool,
        _ swap: (Int, Int) -> Void
    ) {
        var root = lo
        while true {
            var child = 2 * root + 1
            if child >= hi {
                break
            }
            if child + 1 < hi && less(first + child, first + child + 1) {
                child += 1
            }
            if !less(first + root, first + child) {
                return
            }
            swap(first + root, first + child)
            root = child
        }
    }

    /// Go: `heapSort` — the fallback once `limit` bad pivots have been spent.
    private static func heapSort(
        _ a: Int, _ b: Int, _ less: (Int, Int) -> Bool, _ swap: (Int, Int) -> Void
    ) {
        let first = a
        let lo = 0
        let hi = b - a

        // Build the heap with the greatest element on top.
        var i = (hi - 1) / 2
        while i >= 0 {
            siftDown(i, hi, first, less, swap)
            i -= 1
        }

        // Pop, largest first, into the end of the range.
        var j = hi - 1
        while j >= 0 {
            swap(first, first + j)
            siftDown(lo, j, first, less, swap)
            j -= 1
        }
    }

    /// Go: `pdqsort` — pattern-defeating quicksort, without BlockQuicksort's tricks.
    ///
    /// Go recurses on the smaller side and loops on the larger, so `a`/`b` are mutable
    /// and the recursion depth stays logarithmic.
    private static func pdqsort(
        _ aIn: Int, _ bIn: Int, _ limitIn: Int,
        _ less: (Int, Int) -> Bool, _ swap: (Int, Int) -> Void
    ) {
        let maxInsertion = 12

        var a = aIn
        var b = bIn
        var limit = limitIn
        var wasBalanced = true
        var wasPartitioned = true

        while true {
            let length = b - a

            if length <= maxInsertion {
                insertionSort(a, b, less, swap)
                return
            }

            // Too many bad pivots: heapsort's worst case beats quicksort's.
            if limit == 0 {
                heapSort(a, b, less, swap)
                return
            }

            // An imbalanced partition means the input has a pattern worth scattering.
            if !wasBalanced {
                breakPatterns(a, b, swap)
                limit -= 1
            }

            var (pivot, hint) = choosePivot(a, b, less)
            if hint == .decreasing {
                reverseRange(a, b, swap)
                // The pivot was `pivot-a` after the start; reversed, it is that far
                // before the end. (Go credits Rust for the idea.)
                pivot = (b - 1) - (pivot - a)
                hint = .increasing
            }

            // Likely already sorted: try to finish with a few shifts.
            if wasBalanced && wasPartitioned && hint == .increasing {
                if partialInsertionSort(a, b, less, swap) {
                    return
                }
            }

            // Likely many duplicates: split into "equal to the pivot" and "greater".
            if a > 0 && !less(a - 1, pivot) {
                let mid = partitionEqual(a, b, pivot, less, swap)
                a = mid
                continue
            }

            let (mid, alreadyPartitioned) = partition(a, b, pivot, less, swap)
            wasPartitioned = alreadyPartitioned

            let leftLen = mid - a
            let rightLen = b - mid
            let balanceThreshold = length / 8
            if leftLen < rightLen {
                wasBalanced = leftLen >= balanceThreshold
                pdqsort(a, mid, limit, less, swap)
                a = mid + 1
            } else {
                wasBalanced = rightLen >= balanceThreshold
                pdqsort(mid + 1, b, limit, less, swap)
                b = mid
            }
        }
    }

    /// Go: `partition` — one quicksort partition, reporting whether the range was
    /// already partitioned so the caller can stop early next time round.
    private static func partition(
        _ a: Int, _ b: Int, _ pivot: Int,
        _ less: (Int, Int) -> Bool, _ swap: (Int, Int) -> Void
    ) -> (newpivot: Int, alreadyPartitioned: Bool) {
        swap(a, pivot)
        var i = a + 1
        var j = b - 1  // both inclusive of what is left to partition

        while i <= j && less(i, a) { i += 1 }
        while i <= j && !less(j, a) { j -= 1 }
        if i > j {
            swap(j, a)
            return (j, true)
        }
        swap(i, j)
        i += 1
        j -= 1

        while true {
            while i <= j && less(i, a) { i += 1 }
            while i <= j && !less(j, a) { j -= 1 }
            if i > j {
                break
            }
            swap(i, j)
            i += 1
            j -= 1
        }
        swap(j, a)
        return (j, false)
    }

    /// Go: `partitionEqual` — elements equal to the pivot, then elements greater.
    /// Assumes nothing in the range is smaller than the pivot.
    private static func partitionEqual(
        _ a: Int, _ b: Int, _ pivot: Int,
        _ less: (Int, Int) -> Bool, _ swap: (Int, Int) -> Void
    ) -> Int {
        swap(a, pivot)
        var i = a + 1
        var j = b - 1

        while true {
            while i <= j && !less(a, i) { i += 1 }
            while i <= j && less(a, j) { j -= 1 }
            if i > j {
                break
            }
            swap(i, j)
            i += 1
            j -= 1
        }
        return i
    }

    /// Go: `partialInsertionSort` — shift at most 5 out-of-order pairs, and report
    /// whether that finished the job.
    ///
    /// Note both inner shift loops run over the WHOLE range rather than from `a`: the
    /// left one stops at index 1, not at `a + 1`. That is upstream's, and on a
    /// sub-range it can touch elements before `a` — harmless because the guard
    /// `!less(j, j-1)` breaks immediately there, but it is not a typo to be tidied.
    private static func partialInsertionSort(
        _ a: Int, _ b: Int, _ less: (Int, Int) -> Bool, _ swap: (Int, Int) -> Void
    ) -> Bool {
        let maxSteps = 5  // out-of-order pairs to shift
        let shortestShifting = 50  // do not shift on short ranges

        var i = a + 1
        for _ in 0..<maxSteps {
            while i < b && !less(i, i - 1) { i += 1 }

            if i == b {
                return true
            }

            if b - a < shortestShifting {
                return false
            }

            swap(i, i - 1)

            // Shift the smaller one left.
            if i - a >= 2 {
                var j = i - 1
                while j >= 1 {
                    if !less(j, j - 1) {
                        break
                    }
                    swap(j, j - 1)
                    j -= 1
                }
            }
            // Shift the greater one right.
            if b - i >= 2 {
                var j = i + 1
                while j < b {
                    if !less(j, j - 1) {
                        break
                    }
                    swap(j, j - 1)
                    j += 1
                }
            }
        }
        return false
    }

    /// Go: `breakPatterns` — scatter three elements around the middle to defeat inputs
    /// that keep producing imbalanced partitions.
    ///
    /// The randomness is a xorshift seeded with the *length*, so the same length always
    /// scatters the same way. It calls `swap` and never `less`.
    private static func breakPatterns(_ a: Int, _ b: Int, _ swap: (Int, Int) -> Void) {
        let length = b - a
        if length >= 8 {
            var random = Xorshift(length)
            let modulus = nextPowerOfTwo(length)

            var idx = a + (length / 4) * 2 - 1
            while idx <= a + (length / 4) * 2 + 1 {
                var other = Int(random.next() & (UInt64(modulus) - 1))
                if other >= length {
                    other -= length
                }
                swap(idx, a + other)
                idx += 1
            }
        }
    }

    /// Go: `choosePivot` — a static pivot below 8 elements, median-of-three below 50,
    /// and Tukey's ninther above that. The `swaps` count is what produces the hint.
    private static func choosePivot(
        _ a: Int, _ b: Int, _ less: (Int, Int) -> Bool
    ) -> (pivot: Int, hint: SortedHint) {
        let shortestNinther = 50
        let maxSwaps = 4 * 3

        let l = b - a

        var swaps = 0
        var i = a + l / 4 * 1
        var j = a + l / 4 * 2
        var k = a + l / 4 * 3

        if l >= 8 {
            if l >= shortestNinther {
                i = medianAdjacent(i, &swaps, less)
                j = medianAdjacent(j, &swaps, less)
                k = medianAdjacent(k, &swaps, less)
            }
            // The median of the three, left in j.
            j = median(i, j, k, &swaps, less)
        }

        switch swaps {
        case 0:
            return (j, .increasing)
        case maxSwaps:
            return (j, .decreasing)
        default:
            return (j, .unknown)
        }
    }

    /// Go: `order2` — the pair in order, counting how often it had to be flipped.
    private static func order2(
        _ a: Int, _ b: Int, _ swaps: inout Int, _ less: (Int, Int) -> Bool
    ) -> (Int, Int) {
        if less(b, a) {
            swaps += 1
            return (b, a)
        }
        return (a, b)
    }

    /// Go: `median` — the index of the median of three, by three `order2` calls.
    private static func median(
        _ aIn: Int, _ bIn: Int, _ cIn: Int, _ swaps: inout Int, _ less: (Int, Int) -> Bool
    ) -> Int {
        var a = aIn
        var b = bIn
        var c = cIn
        (a, b) = order2(a, b, &swaps, less)
        (b, c) = order2(b, c, &swaps, less)
        (a, b) = order2(a, b, &swaps, less)
        _ = a
        _ = c
        return b
    }

    /// Go: `medianAdjacent` — the median of `a-1`, `a`, `a+1`.
    private static func medianAdjacent(
        _ a: Int, _ swaps: inout Int, _ less: (Int, Int) -> Bool
    ) -> Int {
        median(a - 1, a, a + 1, &swaps, less)
    }

    /// Go: `reverseRange`.
    private static func reverseRange(_ a: Int, _ b: Int, _ swap: (Int, Int) -> Void) {
        var i = a
        var j = b - 1
        while i < j {
            swap(i, j)
            i += 1
            j -= 1
        }
    }
}
