//===----------------------------------------------------------------------===//
// Differential tests for model/histogram/histogram.go — the integer Histogram.
//
// Correctness here is what Go did, not what looks right: every expectation in
// these suites comes from `promoracle`, generated by running the pinned
// Prometheus. See docs/PORTING.md.
//===----------------------------------------------------------------------===//

import GoOracleSupport
import Testing

@testable import PromHistogram

// MARK: - histogram/integer

struct IntegerOut: Codable, Equatable, Sendable {
    let str: String
    let pos: [String]
    let neg: [String]
    /// Null when the histogram has negative buckets, where Go panics rather than
    /// iterating.
    let cum: [String]?
    /// Null for custom buckets, where `ZeroBucket` panics.
    let zero: String?
    let copy: HistJSON
    let copyTo: HistJSON
    let float: FloatHistJSON
    let validate: String
}

@Suite("Integer histogram matches Go")
struct IntegerHistogramTests {

    /// The dirty CopyTo destination the oracle uses. Copying into a populated
    /// histogram of a different schema is what catches a field that `copy(to:)`
    /// forgets to overwrite.
    static func dirtyDestination() -> Histogram {
        Histogram(
            counterResetHint: .gaugeType,
            schema: 3,
            zeroThreshold: 7.5,
            zeroCount: 99,
            count: 123,
            sum: -0.5,
            positiveSpans: [Span(offset: 5, length: 3)],
            negativeSpans: [Span(offset: 2, length: 2)],
            positiveBuckets: [9, 9, 9],
            negativeBuckets: [4, 4],
            customValues: [11, 22])
    }

    @Test("String, iterators, ZeroBucket, Copy, CopyTo and ToFloat")
    func values() throws {
        try Fixtures.check("histogram/integer.jsonl", FixtureCase<HistJSON, IntegerOut>.self) {
            input in
            let h = input.histogram
            var destination = Self.dirtyDestination()
            h.copy(to: &destination)
            return IntegerOut(
                str: h.description,
                pos: drain(h.positiveBucketIterator()),
                neg: drain(h.negativeBucketIterator()),
                cum: h.negativeBuckets.isEmpty ? drain(h.cumulativeBucketIterator()) : nil,
                zero: h.usesCustomBuckets ? nil : h.zeroBucket().description,
                copy: HistJSON(h.copy()),
                copyTo: HistJSON(destination),
                float: FloatHistJSON(h.toFloat()),
                validate: errString(h.validate))
        }
    }

    @Test("Compact at every maxEmptyBuckets")
    func compact() throws {
        struct In: Decodable, Sendable {
            let h: HistJSON
            let maxEmptyBuckets: Int
        }
        try Fixtures.check("histogram/integer-compact.jsonl", FixtureCase<In, HistJSON>.self) {
            input in
            var h = input.h.histogram
            h.compact(maxEmptyBuckets: input.maxEmptyBuckets)
            return HistJSON(h)
        }
    }

    @Test("ReduceResolution, including the histogram left behind on error")
    func reduceResolution() throws {
        struct In: Decodable, Sendable {
            let h: HistJSON
            let targetSchema: Int32
        }
        struct Out: Decodable, Equatable, Sendable {
            let h: HistJSON
            let err: String
        }
        try Fixtures.check("histogram/integer-reduce.jsonl", FixtureCase<In, Out>.self) { input in
            var h = input.h.histogram
            let err = errString { try h.reduceResolution(targetSchema: input.targetSchema) }
            return Out(h: HistJSON(h), err: err)
        }
    }

    @Test("Validate reproduces Go's error text")
    func validate() throws {
        try Fixtures.check("histogram/integer-validate.jsonl", FixtureCase<HistJSON, String>.self) {
            input in
            errString(input.histogram.validate)
        }
    }

    @Test("Equals over every pair of the span-layout corpus")
    func equals() throws {
        struct In: Decodable, Sendable {
            let a: HistJSON
            let b: HistJSON
        }
        try Fixtures.check("histogram/integer-equals.jsonl", FixtureCase<In, Bool>.self) { input in
            input.a.histogram.equals(input.b.histogram)
        }
    }
}

// MARK: - Properties the fixtures cannot state

@Suite("Integer histogram invariants")
struct IntegerHistogramInvariantTests {

    static let sample = Histogram(
        schema: 0,
        zeroThreshold: 0.001,
        zeroCount: 4,
        count: 21,
        sum: 1234.5,
        positiveSpans: [Span(offset: 0, length: 3), Span(offset: 1, length: 1)],
        negativeSpans: [Span(offset: 0, length: 4), Span(offset: 1, length: 1)],
        positiveBuckets: [1, 1, -1, 0],
        negativeBuckets: [1, 2, -2, 1, -1])

    @Test("customValues distinguishes nil from empty, because Go's nil check does")
    func customValuesNilIsNotEmpty() {
        // histogram.go:456 rejects any non-nil CustomValues on an exponential
        // schema, so an empty slice is an error and nil is not. Collapsing the two
        // would be a silent divergence — see the file header.
        var h = Histogram(schema: 0)
        #expect(throws: Never.self) { try h.validate() }
        h.customValues = []
        #expect(throws: HistogramError.expSchemaCustomBounds) { try h.validate() }
    }

    @Test("Equals is not structural equality")
    func equalsIsNotStructural() {
        // Zero-length spans fold into the next non-empty span, so these two
        // describe the same buckets despite different span slices. This is why
        // Histogram deliberately does not conform to Equatable.
        var a = Self.sample
        a.positiveSpans = [Span(offset: 0, length: 2), Span(offset: 1, length: 2)]
        a.positiveBuckets = [1, 1, -1, 0]
        var b = a
        b.positiveSpans = [
            Span(offset: 0, length: 2), Span(offset: 0, length: 0), Span(offset: 1, length: 2),
        ]
        #expect(a.positiveSpans != b.positiveSpans)
        #expect(a.equals(b))
    }

    @Test("Sum is compared by bit pattern, not mathematically")
    func sumBitPattern() {
        var a = Self.sample
        var b = Self.sample
        // -0 == 0 mathematically, but they are different data.
        a.sum = 0
        b.sum = -0.0
        #expect(!a.equals(b))
        // NaN != NaN mathematically, but the same bits are the same data.
        a.sum = .nan
        b.sum = .nan
        #expect(a.equals(b))
    }

    @Test("ToFloat accumulates the deltas into absolute counts")
    func toFloatAccumulates() {
        let fh = Self.sample.toFloat()
        #expect(fh.positiveBuckets == [1, 2, 1, 1])
        #expect(fh.negativeBuckets == [1, 3, 1, 2, 1])
        #expect(fh.count == 21)
        #expect(fh.zeroCount == 4)
        #expect(fh.customValues == nil)
    }

    @Test("ToFloat drops the fields a custom-buckets schema does not use")
    func toFloatCustomBuckets() {
        let h = Histogram(
            schema: HistogramSchema.customBuckets,
            zeroThreshold: 0.001,
            zeroCount: 2,
            count: 4,
            sum: 3,
            positiveSpans: [Span(offset: 0, length: 2)],
            negativeSpans: [Span(offset: 0, length: 1)],
            positiveBuckets: [2, 0],
            negativeBuckets: [1],
            customValues: [1, 2])
        let fh = h.toFloat()
        #expect(fh.zeroThreshold == 0)
        #expect(fh.zeroCount == 0)
        #expect(fh.negativeSpans.isEmpty)
        #expect(fh.negativeBuckets.isEmpty)
        #expect(fh.customValues == [1, 2])
    }

    @Test("a failed ReduceResolution clears the side it was reducing")
    func reduceResolutionClearsOnError() {
        // histogram.go:642 assigns reduceResolution's (nil, nil) result before
        // checking the error, so a rejected histogram is left cleared rather than
        // untouched. Replicated deliberately; a fixture pins it too.
        var h = Histogram(
            schema: 2,
            positiveSpans: [Span(offset: 0, length: 4)],
            positiveBuckets: [1, 1])
        #expect(throws: (any Error).self) { try h.reduceResolution(targetSchema: 0) }
        #expect(h.positiveSpans.isEmpty)
        #expect(h.positiveBuckets.isEmpty)
        // The schema is only updated after both sides succeed.
        #expect(h.schema == 2)
    }

    @Test("ReduceResolution rejects what it cannot do, with Go's wording")
    func reduceResolutionRejections() {
        var custom = Histogram(schema: HistogramSchema.customBuckets, customValues: [1, 2])
        #expect(
            errString { try custom.reduceResolution(targetSchema: 0) }
                == "cannot reduce resolution when there are custom buckets")

        var h = Histogram(schema: 2)
        #expect(
            errString { try h.reduceResolution(targetSchema: HistogramSchema.customBuckets) }
                == "cannot reduce resolution to custom buckets schema")
        #expect(
            errString { try h.reduceResolution(targetSchema: 2) }
                == "cannot reduce resolution from schema 2 to 2")
        #expect(
            errString { try h.reduceResolution(targetSchema: 3) }
                == "cannot reduce resolution from schema 2 to 3")
    }

    @Test("the two spans/buckets mismatch messages are not interchangeable")
    func spansBucketsMessages() {
        // generic.go:817 vs generic.go:883 — the mid-loop error reports what it
        // has, the after-loop error reports what the spans need. Getting these
        // the wrong way round is invisible without a fixture.
        var tooFew = Histogram(
            schema: 2, positiveSpans: [Span(offset: 0, length: 4)], positiveBuckets: [1, 1])
        #expect(
            errString { try tooFew.reduceResolution(targetSchema: 0) }
                == "have 2 buckets but spans need more: histogram spans specify different number of buckets than provided"
        )

        var tooMany = Histogram(
            schema: 2, positiveSpans: [Span(offset: 0, length: 1)], positiveBuckets: [1, 1, 1])
        #expect(
            errString { try tooMany.reduceResolution(targetSchema: 0) }
                == "spans need 1 buckets, have 3 buckets: histogram spans specify different number of buckets than provided"
        )
    }

    @Test("the iterator converts a negative running count the way Go does")
    func negativeCountConversion() {
        // generic.go:202 — BC(currCount) is a numeric conversion, so an invalid
        // histogram's negative delta becomes a huge uint64 rather than clamping
        // to 0. Clamping would hide the divergence instead of surfacing it.
        let h = Histogram(
            schema: 0, positiveSpans: [Span(offset: 0, length: 1)], positiveBuckets: [-1])
        var it = h.positiveBucketIterator()
        let advanced = it.next()
        #expect(advanced)
        #expect(it.at().count == UInt64.max)
    }
}
