//===----------------------------------------------------------------------===//
// `storage/merge.go`, `lazy.go`, `secondary.go` and `generic.go` Part A — the vertical merge.
//
// The corpus (`Fixtures/storage/merge.jsonl`) is generated by driving upstream's own
// `storage.NewMergeQuerier` / `NewMergeChunkQuerier` over **real block queriers** written by
// `oracle/blockfixture.go` and opened with `tsdb.OpenBlock`. This side mirrors that exactly:
// `PromBlock.BlockQuerier` over the same block bytes, through `newMergeQuerier`.
//
// **The stubs are leaves, on both sides.** A real block querier cannot error, cannot warn and cannot
// fail to close, and those three are most of what makes merge.go's plumbing interesting — so the
// oracle has a `stubQuerier` and so does this file, with the same four knobs. Everything above them
// is ported code on this side and upstream code on the other; §6w's lesson is about the harness
// standing in for the code under test, not about a data source being synthetic.
//
// The four passes are the oracle's, in the oracle's order, because a secondary querier PANICS if it
// is `Select`-ed again after the first `Next()` of any set it produced — so each pass builds its own
// queriers.
//===----------------------------------------------------------------------===//

import Foundation
import GoCompat
import GoOracleSupport
import PromAnnotations
import PromBlock
import PromChunkEnc
import PromChunks
import PromEncoding
import PromFS
import PromIndex
import PromLabels
import PromStorage
import Testing

// MARK: - Wire shapes

struct MergeSeriesIn: Codable, Sendable {
    var labels: [[String]]
    var chunks: [[[Int64]]]?
}

struct MergeSourceIn: Codable, Sendable {
    var kind: String
    var secondary: Bool?

    var series: [MergeSeriesIn]?
    var indexHex: String?
    var metaHex: String?
    var segHexes: [String]?

    /// `errAfter` > 0: the set yields that many series and only then errors. See the oracle.
    var errAfter: Int?
    var selectErr: String?
    var selectWarn: String?
    var labelErr: String?
    var labelWarn: String?
    var closeErr: String?
    var values: [String]?
    var names: [String]?
}

struct MergeIn: Codable, Sendable {
    var sources: [MergeSourceIn]
    var mint: Int64
    var maxt: Int64
    var matchers: [[String]]?
    var limit: Int
    var nilHints: Bool
    var chunkMerger: String
    var labelName: String
    var labelLimit: Int
    var nilLabelHints: Bool
}

struct MergeOut: Decodable, Equatable, Sendable {
    var querierKind: String
    var chunkQuerierKind: String

    var labelSets: [String]
    var sampleTimes: [[Int64]]
    var sampleVals: [[String]]
    var seekTimes: [[Int64]]
    var seekVals: [[String]]
    var selectErr: String
    var selectWarnings: [String]
    /// `err()` and `warnings()` read BEFORE the first `next()` — what `Lazy.swift` is for.
    var preSelectErr: String
    var preSelectWarnings: [String]

    var chunkLabelSets: [String]
    var chunkRanges: [[[Int64]]]
    var chunkBytes: [[String]]
    var chunkErr: String
    var chunkWarnings: [String]

    var labelValues: [String]
    var labelValuesWarnings: [String]
    var labelValuesErr: String
    var labelNames: [String]
    var labelNamesWarnings: [String]
    var labelNamesErr: String

    var closeErr: String
    var openErr: String
}

// MARK: - The leaf stubs

/// The oracle's `errors.New(msg)`.
private struct StubError: Error, CustomStringConvertible {
    let message: String
    var description: String { message }
}

/// The oracle's `delayedErrSeriesSet` — yields `n` one-sample series and then errors.
///
/// The only route to `GenericMergeSeriesSet.err()`: a set that errors on its FIRST `next()` is
/// caught by the pre-advance in `newGenericMergeSeriesSet` and collapses the merge into an
/// `ErrorOnlySeriesSet` instead.
private final class DelayedErrSeriesSet: SeriesSet {
    private let n: Int
    private let message: String
    private var i = 0

    init(n: Int, message: String) {
        self.n = n
        self.message = message
    }

    func next() -> Bool {
        if i >= n { return false }
        i += 1
        return true
    }

    func at() -> (any Series)? {
        newListSeries(
            Labels([Label("__name__", String(format: "late%02d", i - 1))]),
            [FSample(st: 0, t: Int64(i) * 10, f: Double(i))])
    }

    func err() -> (any Error)? {
        if i >= n && !message.isEmpty { return StubError(message: message) }
        return nil
    }

    func warnings() -> Annotations { Annotations() }
}

/// The oracle's `warnSeriesSet` — empty, but carrying warnings.
private final class WarnSeriesSet: SeriesSet {
    private let ws: Annotations
    init(_ ws: Annotations) { self.ws = ws }
    func next() -> Bool { false }
    func at() -> (any Series)? { nil }
    func err() -> (any Error)? { nil }
    func warnings() -> Annotations { ws }
}

private final class WarnChunkSeriesSet: ChunkSeriesSet {
    private let ws: Annotations
    init(_ ws: Annotations) { self.ws = ws }
    func next() -> Bool { false }
    func at() -> (any ChunkSeries)? { nil }
    func err() -> (any Error)? { nil }
    func warnings() -> Annotations { ws }
}

/// The oracle's `stubQuerier`.
private final class StubQuerier: Querier {
    let spec: MergeSourceIn
    init(_ spec: MergeSourceIn) { self.spec = spec }

    func select(
        _ ctx: GoContext, sortSeries: Bool, hints: SelectHints?, matchers: [Matcher]
    ) -> any SeriesSet {
        if let n = spec.errAfter, n > 0 {
            return DelayedErrSeriesSet(n: n, message: spec.selectErr ?? "")
        }
        if let e = spec.selectErr, !e.isEmpty { return errSeriesSet(StubError(message: e)) }
        if let w = spec.selectWarn, !w.isEmpty {
            var ws = Annotations()
            ws.add(error: StubError(message: w))
            return WarnSeriesSet(ws)
        }
        return emptySeriesSet()
    }

    func labelValues(
        _ ctx: GoContext, name: String, hints: LabelHints?, matchers: [Matcher]
    ) throws -> (values: [String], warnings: Annotations) {
        if let e = spec.labelErr, !e.isEmpty { throw StubError(message: e) }
        var ws = Annotations()
        if let w = spec.labelWarn, !w.isEmpty { ws.add(error: StubError(message: w)) }
        return (spec.values ?? [], ws)
    }

    func labelNames(
        _ ctx: GoContext, hints: LabelHints?, matchers: [Matcher]
    ) throws -> (names: [String], warnings: Annotations) {
        if let e = spec.labelErr, !e.isEmpty { throw StubError(message: e) }
        var ws = Annotations()
        if let w = spec.labelWarn, !w.isEmpty { ws.add(error: StubError(message: w)) }
        return (spec.names ?? [], ws)
    }

    func close() throws {
        if let e = spec.closeErr, !e.isEmpty { throw StubError(message: e) }
    }
}

private final class StubChunkQuerier: ChunkQuerier {
    let spec: MergeSourceIn
    private let sample: StubQuerier

    init(_ spec: MergeSourceIn) {
        self.spec = spec
        self.sample = StubQuerier(spec)
    }

    func select(
        _ ctx: GoContext, sortSeries: Bool, hints: SelectHints?, matchers: [Matcher]
    ) -> any ChunkSeriesSet {
        if let e = spec.selectErr, !e.isEmpty { return errChunkSeriesSet(StubError(message: e)) }
        if let w = spec.selectWarn, !w.isEmpty {
            var ws = Annotations()
            ws.add(error: StubError(message: w))
            return WarnChunkSeriesSet(ws)
        }
        return emptyChunkSeriesSet()
    }

    func labelValues(
        _ ctx: GoContext, name: String, hints: LabelHints?, matchers: [Matcher]
    ) throws -> (values: [String], warnings: Annotations) {
        try sample.labelValues(ctx, name: name, hints: hints, matchers: matchers)
    }

    func labelNames(
        _ ctx: GoContext, hints: LabelHints?, matchers: [Matcher]
    ) throws -> (names: [String], warnings: Annotations) {
        try sample.labelNames(ctx, hints: hints, matchers: matchers)
    }

    func close() throws { try sample.close() }
}

// MARK: - The block shim

/// A `BlockQuerierIndex` over one index file's bytes — `SeriesSetFileIndex` and `LabelFileIndex`
/// from `PromBlockTests`, joined, because a merge querier needs both halves at once.
private struct MergeFileIndex: SeriesIndex, PostingsIndex, LabelQueryIndex {
    let bytes: [UInt8]
    let toc: IndexTOC
    let sparse: [String: [PostingOffset]]
    let symbols: IndexSymbols

    init(_ bytes: [UInt8]) throws {
        self.bytes = bytes
        (self.toc, self.sparse, self.symbols) = try bytes.withUnsafeBytes { buf in
            let bs = ByteSlice(buf)
            let toc = try IndexTOC(byteSlice: bs)
            return (
                toc,
                try buildPostingsOffsetIndex(bs, postingsTable: toc.postingsTable),
                try IndexSymbols(byteSlice: bs, version: indexFormatV2, off: Int(toc.symbols))
            )
        }
    }

    func postings(name: String, values: [String]) throws -> any Postings {
        try bytes.withUnsafeBytes { buf in
            merge(
                try indexPostings(
                    ByteSlice(buf), postingsTable: toc.postingsTable, sparse: sparse, name: name,
                    values: values))
        }
    }

    func postingsForLabelMatching(name: String, match: @escaping (String) -> Bool) throws
        -> any Postings
    {
        try bytes.withUnsafeBytes { buf in
            try indexPostingsForLabelMatching(
                ByteSlice(buf), postingsTable: toc.postingsTable, sparse: sparse, name: name,
                match: match)
        }
    }

    func postingsForAllLabelValues(name: String) throws -> any Postings {
        try bytes.withUnsafeBytes { buf in
            try indexPostingsForLabelMatching(
                ByteSlice(buf), postingsTable: toc.postingsTable, sparse: sparse, name: name,
                match: nil)
        }
    }

    func series(_ ref: SeriesRef) throws -> (
        labels: [(name: String, value: String)], chunks: [DecodedChunkMeta]
    )? {
        try bytes.withUnsafeBytes { buf in
            let decoded = try readSeries(
                ByteSlice(buf), id: ref.rawValue, version: indexFormatV2,
                lookupSymbol: { try symbols.lookup($0) })
            return (decoded.labels, decoded.chunks)
        }
    }

    func labelValues(name: String) throws -> [String] {
        try bytes.withUnsafeBytes { buf in
            try indexLabelValues(
                ByteSlice(buf), postingsTable: toc.postingsTable, sparse: sparse, name: name,
                limit: 0)
        }
    }

    func labelNamesFor(_ postings: any Postings) throws -> [String] {
        let ids = try expandPostings(postings).map(\.rawValue)
        return try bytes.withUnsafeBytes { buf in
            try indexLabelNamesFor(
                ByteSlice(buf), version: indexFormatV2, seriesIDs: ids,
                lookupSymbol: { try symbols.lookup($0) })
        }
    }

    func labelNames() throws -> [String] { indexLabelNames(sparse) }
}

/// A `BlockChunkSource` over a block's chunk segments — `PromBlockTests`' `SegmentChunkSource`.
private struct MergeChunkSource: BlockChunkSource {
    let reader: ChunkReader

    init(segmentHexes: [String]) throws {
        let fs = InMemoryFS()
        try fs.createDirectory("chunks")
        for (i, hex) in segmentHexes.enumerated() {
            let w = try fs.createFile(String(format: "chunks/%06d", i + 1))
            try w.append(unhexMG(hex))
            try w.close()
        }
        self.reader = try ChunkReader(fs: fs, dir: "chunks")
    }

    func chunkOrIterable(_ meta: DecodedChunkMeta, copyHeadChunk: Bool) throws -> ChunkOrIterable {
        ChunkOrIterable(chunk: try reader.chunk(ref: ChunkRef(rawValue: meta.ref)))
    }
}

// MARK: - Helpers

private func unhexMG(_ s: String) -> [UInt8] {
    var out: [UInt8] = []
    out.reserveCapacity(s.utf8.count / 2)
    var i = s.startIndex
    while i < s.endIndex {
        let j = s.index(i, offsetBy: 2)
        out.append(UInt8(s[i..<j], radix: 16)!)
        i = j
    }
    return out
}

private func matcherMG(_ spec: [String]) throws -> Matcher {
    let type: MatchType
    switch spec[0] {
    case "=": type = .equal
    case "!=": type = .notEqual
    case "=~": type = .regexp
    case "!~": type = .notRegexp
    default: fatalError("unknown matcher type \(spec[0])")
    }
    return try Matcher(type, spec[1], spec[2])
}

/// The oracle's `fbits` — `fmt.Sprintf("%016x", math.Float64bits(f))`.
///
/// `%016llx`, not `%016x`: `String(format:)` reads a 32-bit argument for `%x`, so every double whose
/// low word is zero — 0.0, 1.0, 2.0, 100.0 — rendered as `0000000000000000`. That is exactly the
/// shape of a harness bug that passes its first case and silently loses the rest.
private func fbitsMG(_ v: Double) -> String { String(format: "%016llx", v.bitPattern) }

/// The oracle's `sortedWarnings`. Sorted for the reason recorded there: `annotations.Annotations`
/// is a Go map, so there is no order to be exact against.
private func sortedWarningsMG(_ ws: Annotations) -> [String] {
    ws.asErrors().map { String(describing: $0) }.sorted()
}

private func errStringMG(_ e: (any Error)?) -> String {
    guard let e else { return "" }
    return String(describing: e)
}

/// The Go type name of what a constructor returned. A pure NAME translation — the mapping has one
/// entry per Go type and no conditions, so the switch it pins stays upstream's.
private func querierKindMG(_ q: any Querier) -> String {
    switch q {
    case is NoopQuerier: return "storage.noopQuerier"
    case is BlockQuerier: return "*tsdb.blockQuerier"
    case is QuerierAdapter: return "*storage.querierAdapter"
    case is StubQuerier: return "*main.stubQuerier"
    default: return "?\(type(of: q))"
    }
}

private func chunkQuerierKindMG(_ q: any ChunkQuerier) -> String {
    switch q {
    case is NoopChunkQuerier: return "storage.noopChunkQuerier"
    case is BlockChunkQuerier: return "*tsdb.blockChunkQuerier"
    case is ChunkQuerierAdapter: return "*storage.chunkQuerierAdapter"
    case is StubChunkQuerier: return "*main.stubChunkQuerier"
    default: return "?\(type(of: q))"
    }
}

// MARK: - The suite

@Suite("storage: the vertical merge")
struct StorageMergeTests {

    @Test("every committed merge matches Go")
    func matchesGo() throws {
        try Fixtures.check("storage/merge.jsonl", FixtureCase<MergeIn, MergeOut>.self) { input in
            var out = MergeOut(
                querierKind: "", chunkQuerierKind: "", labelSets: [], sampleTimes: [],
                sampleVals: [], seekTimes: [], seekVals: [], selectErr: "", selectWarnings: [],
                preSelectErr: "", preSelectWarnings: [],
                chunkLabelSets: [], chunkRanges: [], chunkBytes: [], chunkErr: "",
                chunkWarnings: [], labelValues: [], labelValuesWarnings: [], labelValuesErr: "",
                labelNames: [], labelNamesWarnings: [], labelNamesErr: "", closeErr: "",
                openErr: "")

            let ctx = GoContext.background()

            // The block sources' readers, opened once. `nil` for a non-block source.
            var indexes: [MergeFileIndex?] = []
            var sources: [MergeChunkSource?] = []
            for s in input.sources {
                if s.kind == "block", let ih = s.indexHex {
                    indexes.append(try MergeFileIndex(unhexMG(ih)))
                    sources.append(try MergeChunkSource(segmentHexes: s.segHexes ?? []))
                } else {
                    indexes.append(nil)
                    sources.append(nil)
                }
            }

            // Fresh queriers per pass: a secondary querier refuses a second `Select` once any of
            // its sets has been advanced.
            func buildQueriers() -> (primaries: [(any Querier)?], secondaries: [(any Querier)?]) {
                var primaries: [(any Querier)?] = []
                var secondaries: [(any Querier)?] = []
                for (i, s) in input.sources.enumerated() {
                    var q: (any Querier)?
                    switch s.kind {
                    case "block":
                        q = BlockQuerier(
                            index: indexes[i]!, chunks: sources[i]!, mint: input.mint,
                            maxt: input.maxt)
                    case "stub": q = StubQuerier(s)
                    case "noop": q = NoopQuerier()
                    default: q = nil
                    }
                    if s.secondary == true { secondaries.append(q) } else { primaries.append(q) }
                }
                return (primaries, secondaries)
            }
            func buildChunkQueriers() -> (
                primaries: [(any ChunkQuerier)?], secondaries: [(any ChunkQuerier)?]
            ) {
                var primaries: [(any ChunkQuerier)?] = []
                var secondaries: [(any ChunkQuerier)?] = []
                for (i, s) in input.sources.enumerated() {
                    var q: (any ChunkQuerier)?
                    switch s.kind {
                    case "block":
                        q = BlockChunkQuerier(
                            index: indexes[i]!, chunks: sources[i]!, mint: input.mint,
                            maxt: input.maxt)
                    case "stub": q = StubChunkQuerier(s)
                    case "noop": q = NoopChunkQuerier()
                    default: q = nil
                    }
                    if s.secondary == true { secondaries.append(q) } else { primaries.append(q) }
                }
                return (primaries, secondaries)
            }

            let ms: [Matcher] =
                (input.matchers ?? []).isEmpty
                ? [try Matcher(.equal, "", "")]
                : try (input.matchers ?? []).map { try matcherMG($0) }
            let hints: SelectHints? =
                input.nilHints
                ? nil : SelectHints(start: input.mint, end: input.maxt, limit: input.limit)
            let labelHints: LabelHints? =
                input.nilLabelHints ? nil : LabelHints(limit: input.labelLimit)

            // --- pass 1: the sample merge.
            do {
                let (p, s) = buildQueriers()
                let q = newMergeQuerier(
                    primaries: p, secondaries: s, mergeFn: chainedSeriesMerge)
                out.querierKind = querierKindMG(q)
                let set = q.select(ctx, sortSeries: false, hints: hints, matchers: ms)
                // Before ANY next: the lazy set has not initialised.
                out.preSelectErr = errStringMG(set.err())
                out.preSelectWarnings = sortedWarningsMG(set.warnings())
                while set.next() {
                    guard let sr = set.at() else {
                        // Go cannot reach this — its adapter type-asserts and would panic — so the
                        // sentinel is what makes "the port answered nil where Go answered a series"
                        // a diff rather than a silently shorter loop.
                        out.labelSets.append("<nil>")
                        out.sampleTimes.append([])
                        out.sampleVals.append([])
                        continue
                    }
                    out.labelSets.append(sr.labels().description)
                    var ts: [Int64] = []
                    var vs: [String] = []
                    let it = sr.iterator(nil)
                    while it.next() != .none {
                        let (t, v) = it.at()
                        ts.append(t)
                        vs.append(fbitsMG(v))
                    }
                    out.sampleTimes.append(ts)
                    out.sampleVals.append(vs)
                }
                out.selectErr = errStringMG(set.err())
                out.selectWarnings = sortedWarningsMG(set.warnings())
                try? q.close()
            }

            // --- pass 2: the seek script, with anchors from pass 1's own timestamps.
            do {
                let (p, s) = buildQueriers()
                let q = newMergeQuerier(
                    primaries: p, secondaries: s, mergeFn: chainedSeriesMerge)
                let set = q.select(ctx, sortSeries: false, hints: hints, matchers: ms)
                var idx = 0
                while set.next() {
                    guard let sr = set.at() else {
                        out.seekTimes.append([])
                        out.seekVals.append([])
                        idx += 1
                        continue
                    }
                    var t0 = input.mint
                    var tmid = input.mint + (input.maxt - input.mint) / 2
                    var tlast = input.maxt
                    if idx < out.sampleTimes.count, !out.sampleTimes[idx].isEmpty {
                        let ts = out.sampleTimes[idx]
                        t0 = ts[0]
                        tmid = ts[ts.count / 2]
                        tlast = ts[ts.count - 1]
                    }
                    let it = sr.iterator(nil)
                    var res: [Int64] = []
                    var vals: [String] = []
                    func record(_ vt: ValueType) {
                        if vt == .none {
                            res.append(-(1 << 62))
                            vals.append("")
                        } else {
                            let (t, v) = it.at()
                            res.append(t)
                            vals.append(fbitsMG(v))
                        }
                    }
                    record(it.next())
                    record(it.seek(t0))
                    record(it.next())
                    record(it.seek(tmid))
                    record(it.next())
                    record(it.seek(t0))
                    record(it.next())
                    record(it.seek(tlast))
                    record(it.next())
                    record(it.seek(tlast + 1))
                    record(it.next())
                    out.seekTimes.append(res)
                    out.seekVals.append(vals)
                    idx += 1
                }
                try? q.close()
            }

            // --- pass 3: the chunk merge.
            do {
                let (p, s) = buildChunkQueriers()
                let mf: VerticalChunkSeriesMergeFunc =
                    input.chunkMerger == "concat"
                    ? newConcatenatingChunkSeriesMerger()
                    : newCompactingChunkSeriesMerger(chainedSeriesMerge)
                let cq = newMergeChunkQuerier(primaries: p, secondaries: s, mergeFn: mf)
                out.chunkQuerierKind = chunkQuerierKindMG(cq)
                let set = cq.select(ctx, sortSeries: false, hints: hints, matchers: ms)
                while set.next() {
                    guard let cs = set.at() else {
                        out.chunkLabelSets.append("<nil>")
                        out.chunkRanges.append([])
                        out.chunkBytes.append([])
                        continue
                    }
                    out.chunkLabelSets.append(cs.labels().description)
                    var rs: [[Int64]] = []
                    var bs: [String] = []
                    let it = cs.iterator(nil)
                    while it.next() {
                        let m = it.at()
                        rs.append([m.minTime, m.maxTime])
                        bs.append(
                            (m.chunk?.bytes ?? []).map { String(format: "%02x", $0) }.joined())
                    }
                    out.chunkRanges.append(rs)
                    out.chunkBytes.append(bs)
                }
                out.chunkErr = errStringMG(set.err())
                out.chunkWarnings = sortedWarningsMG(set.warnings())
                try? cq.close()
            }

            // --- pass 4: the label queries, and Close.
            do {
                let (p, s) = buildQueriers()
                let q = newMergeQuerier(
                    primaries: p, secondaries: s, mergeFn: chainedSeriesMerge)
                do {
                    let r = try q.labelValues(
                        ctx, name: input.labelName, hints: labelHints, matchers: ms)
                    out.labelValues = r.values
                    out.labelValuesWarnings = sortedWarningsMG(r.warnings)
                } catch {
                    out.labelValuesErr = String(describing: error)
                }
                do {
                    let r = try q.labelNames(ctx, hints: labelHints, matchers: ms)
                    out.labelNames = r.names
                    out.labelNamesWarnings = sortedWarningsMG(r.warnings)
                } catch {
                    out.labelNamesErr = String(describing: error)
                }
                do { try q.close() } catch { out.closeErr = String(describing: error) }
            }

            return out
        }
    }
}
